model:
  model_name: resnet101
  pretrained: True
  softmax: True
  ckpt_load: ~
  freeze_layers: ["layer1", "layer2"]

trainer:
  n_epochs: 3
  optimizer: "Adam"
  lr_scheduler: ~ #"cosine"
  max_lr: !!float 5e-2
  min_lr: !!float 1e-4

  ckpt_load: ~
  ckpt_dir: "./ckpts"
  batch_size: 16
  save_interval: 1

  augmentations: False
  log_interval: 1
  onnx:
    save: False
    path2save: ~

validation_intermediate:
  validate: True
  interval: 1

# validation_final:
#   validate: False
#   testset: "val"

mlflow:
  exp_name: base
  tracking_uri: http://127.0.0.1:5000
  artifact_root: .logs/ml-flow
