model:
  model_name: resnet101
  pretrained: True
  softmax: True
  ckpt_load: "last"
  freeze_layers: ["layer1", "layer2"]

trainer:
  n_epochs: 0
  optimizer: "Adam"
  lr_scheduler: "cosine"
  max_lr: !!float 5e-3
  min_lr: !!float 1e-7

  batch_size: 16
  save_interval: 1

  augmentations: False
  log_interval: 1

validation_intermediate:
  validate: True
  interval: 1

artifacts:
  dirpath: "ckpts"
# validation_final:
#   validate: False
#   testset: "val"
